### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jimhop19**
老師你好，我是王文煦，這是本週任務的測試網址，再請老師幫忙看一下，謝謝！
http://52.64.119.167:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by jimhop19** [comment]
I've solved the problem. It might be OK now.
Please try again!
http://52.64.119.167:3000/
Sorry for the inconvenience.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should redirect user to homepage if user visit /booking without signing in.
2. We should show no booking data message without any other form elements if there is no booking data.

**Comment by jimhop19** [comment]
I've revised the code.Please check the result.Thank you so much!
http://52.64.119.167:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
